<?php

namespace AppBundle\Repository;

/**
 * CaratulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaratulaRepository extends \Doctrine\ORM\EntityRepository
{
}
