<?php

namespace AppBundle\Repository;

/**
 * CategorizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
