<?php

namespace AppBundle\Repository;

/**
 * EstandarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstandarRepository extends \Doctrine\ORM\EntityRepository
{
}
