<?php

namespace AppBundle\Repository;

/**
 * FiltroResumenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiltroResumenRepository extends \Doctrine\ORM\EntityRepository
{
}
