<?php

namespace AppBundle\Repository;

/**
 * PlantillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantillaRepository extends \Doctrine\ORM\EntityRepository
{
}
