<?php

namespace AppBundle\Repository;

/**
 * SubRutinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubRutinaRepository extends \Doctrine\ORM\EntityRepository
{
}
