security:
    providers:
            in_memory:
                memory: 
                    users:
                        ryan:
                            password: ryanpass
                            roles: 'ROLE_USER'
                        admin:
                            password: kitten
                            roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
    # require ROLE_ADMIN for /admin*
        - { path: '^/admin', roles: ROLE_ADMIN }