<?php

namespace AppBundle\Repository\FormularioA;

/**
 * ActaSocietariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActaSocietariaRepository extends \Doctrine\ORM\EntityRepository
{
}
