<?php

namespace AppBundle\Repository\FormularioA;

/**
 * AFIPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AFIPRepository extends \Doctrine\ORM\EntityRepository
{
}
