<?php

namespace AppBundle\Repository\FormularioA;

/**
 * APIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APIRepository extends \Doctrine\ORM\EntityRepository
{
}
