<?php

namespace AppBundle\Repository\FormularioA;

/**
 * ContratoSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratoSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
