<?php

namespace AppBundle\Repository\FormularioA;

/**
 * DniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DniRepository extends \Doctrine\ORM\EntityRepository
{
}
