<?php

namespace AppBundle\Repository\FormularioA;

/**
 * DomicilioRealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomicilioRealRepository extends \Doctrine\ORM\EntityRepository
{
}
