<?php

namespace AppBundle\Repository\FormularioA;

/**
 * DomicilioLegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomicilioLegalRepository extends \Doctrine\ORM\EntityRepository
{
}
