<?php

namespace AppBundle\Repository\FormularioA;

/**
 * UsoConformeSueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsoConformeSueloRepository extends \Doctrine\ORM\EntityRepository
{
}
