<?php

namespace AppBundle\Repository\FormularioA;

/**
 * UsoConformeDeSueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsoConformeDeSueloRepository extends \Doctrine\ORM\EntityRepository
{
}
